/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum SalaryComponentType {
    SALARY = 'SALARY',
    GASOLINE_MONEY = 'GASOLINE_MONEY',
    WOOD_MONEY = 'WOOD_MONEY',
    DAILY_SALARY = 'DAILY_SALARY',
    HOURLY_SALARY = 'HOURLY_SALARY',
    ABSENCE_DEDUCTION = 'ABSENCE_DEDUCTION',
    LATE_DEDUCTION = 'LATE_DEDUCTION',
    ILLEGAL_DEDUCTION = 'ILLEGAL_DEDUCTION',
    BAIL = 'BAIL',
    ACCUMULATED_INSURANCE_MONEY = 'ACCUMULATED_INSURANCE_MONEY',
    OT = 'OT',
    DEDUCT_THE_MONEY_IN_ADVANCE = 'DEDUCT_THE_MONEY_IN_ADVANCE',
    INSURANCE = 'INSURANCE',
    WATER_AND_ELECTRICITY_BILLS = 'WATER_AND_ELECTRICITY_BILLS',
    DAMAGED_EQUIPMENT_COST = 'DAMAGED_EQUIPMENT_COST',
    LEASING = 'LEASING',
}
